name: ui_components
description: "Ui components required for developing full-fledged flutter app."
version: 0.0.1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
