name: ui_components
description: "Ui components required for developing full-fledged flutter app."
version: 1.0.0+5
repository: https://github.com/pintusingh28/flutter-packages/tree/main/ui_components
issue_tracker: https://github.com/pintusingh28/flutter-packages/issues

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
